### ISSUE TITLE
Question about the image resolution

### ISSUE THREAD

**Issue by zclhit** [alvarouc/smri_gen#1]
Thanks for your generous sharing of this sMRI data generator!:)
As a beginner of sMRI data analyzer, here I have one question:
Normally sMRI data are in high resolution and here from the ipynb files of your project the raw sMRI are in low resolution, so is that your project's purpose are generator some useful information from sMRI which can be used as a feature for the classification of Disease Group and Normal Controls?
I have to say sorry because my English is poor and I hope you can understand my Issue.
Anyway, hope you can update this generator soon!

**Comment by alvarouc** [comment]
Thanks for your interest. The example is for a low resolution image indeed, however you can use it on any resolution as long as ICA converges for the number of components you choose. 

I would recommend more components for higher resolution images. Try 15 or more

For more information, please go to http://repository.unm.edu/handle/1928/32266
